# {% if storage_type == 'lso' -%}
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ pin_node2 }}
  storageClassDevices:
    - storageClassName: local-sc
      volumeMode: Block
      fsType: ext4
      devicePaths:
        - /dev/disk/by-id/{{ lso_disk_id }}
---
# {%- endif %}
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: hammerdb-vm
  namespace: benchmark-operator
spec:
  system_metrics:
    collection: False
  #   prom_url: "{{ prom_url }}"
  #   es_url: "{{ es_url }}"
  #   prom_token: "{{ prom_token }}"
  #   metrics_profile: "{{ metrics_profile }}"
  #   index_name: {{ sm_index_name }}
  # elasticsearch:
  #   url: "{{ es_url }}"
  #   index_name: {{ es_index_name }}
  metadata:
    collection: false
  workload:
    name: hammerdb
    args:
      pin: True
      pin_node: vinayakb1709-cp-1-ad1.private2.openshiftvcn.oraclevcn.com
      db_type: "mariadb"
      timed_test: true
      test_type: "tpc-c"
      # true only for first run to build schema
      db_init: true
      db_benchmark: true
      db_server: mssql-deployment.mssql-db
      db_port: "1433"
      db_warehouses: 96
      db_num_workers: 32
      db_user: "SA"
      db_pass: "s3curePasswordString"
      db_name: "tpcc"
      transactions: 100000
      raiseerror: "false"
      keyandthink: "false"
      driver: "timed"
      rampup: 1
      runtime: 1
      allwarehouse: false
      timeprofile: false
      async_scale: false
      async_client: 10
      async_verbose: false
      async_delay: 1000
      samples: 1
      # database specific variables
      # mssql:
      db_mssql_tcp: "true"
      db_mssql_azure: "false"
      db_mssql_authentication: "windows"
      db_mssql_linux_authent: "sql"
      db_mssql_odbc_driver: "ODBC Driver 13 for SQL Server"
      db_mssql_linux_odbc: "ODBC Driver 17 for SQL Server"
      db_mssql_imdb: "false"
      db_mssql_bucket: 1
      db_mssql_durability: "SCHEMA_AND_DATA"
      db_mssql_checkpoint: "false"
      # mariadb:
      db_mysql_storage_engine: "innodb"
      db_mysql_partition: "false"
      db_mysql_socket: "/var/lib/mysql/mysql.sock"
      # postgresql
      db_postgresql_superuser: "postgres"
      db_postgresql_superuser_pass: "postgres"
      db_postgresql_defaultdbase: "tpcc"
      db_postgresql_vacuum: "false"
      db_postgresql_dritasnap: "false"
      db_postgresql_oracompat: "false"
      db_postgresql_storedprocs: "false"
      kind: vm
      client_vm:
        dedicatedcpuplacement: false
        sockets: 32
        cores: 1
        threads: 1
        image: quay.io/cloud-bulldozer/centos-stream8-mssql2019-container-disk:latest
        limits:
          memory: 32Gi
        requests:
          memory: 32Gi
        network:
          front_end: masquerade
          multiqueue:
            enabled: false # if set to true, highly recommend to set selinux to permissive on the nodes where the vms would be scheduled
            queues: 0 # must be given if enabled is set to true and ideally should be set to vcpus ideally so sockets*threads*cores, your image must've ethtool installed
        extra_options:
          - none
          #- hostpassthrough
        # ODF PVC
        pvc: True
        # {%- if storage_type == 'lso' %}
        pvc_storageclass: local-sc
        pvc_pvcaccessmode: ReadWriteOnce
        # {%- else %}
        # pvc_storageclass: ocs-storagecluster-ceph-rbd
        # Can be one of ReadWriteOnce,ReadOnlyMany,ReadWriteMany Default: ReadWriteOnce
        # pvc_pvcaccessmode: ReadWriteMany
        # {%- endif %}
        # Can be one of Filesystem,Block Default: Filesystem
        pvc_pvcvolumemode: Block
        pvc_storagesize: 100Gi
        # HostPath - Configuring SELinux on cluster workers
        hostpath: false # enable for hostpath
        hostpath_path: /var/tmp/disk.img
        hostpath_storagesize: 100Gi