apiVersion: v1
kind: Namespace
metadata:
  name: postgres-db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: postgres-persistent-storage
    namespace: postgres-db
spec:
    storageClassName: oci-bv
    accessModes: [ "ReadWriteOnce" ]
    volumeMode: Filesystem
    resources:
      requests:
        storage: 15Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-config
  namespace: postgres-db
data:
  custom.pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             all            trust
  custom.perf.conf: |
    autovacuum = 'off'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        type: postgres-database-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: vinayakb1709-cp-1-ad1.private2.openshiftvcn.oraclevcn.com
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          # docker.io/centos/postgresql-10-centos8:latest - rate limit issue
          image: quay.io/ebattat/postgresql-10-centos8:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: '32'
              memory: 32Gi
            limits:
              cpu: '32'
              memory: 32Gi
          env:
            - name: POSTGRESQL_USER
              value: "test"
            - name: POSTGRESQL_PASSWORD
              value: "test"
            - name: POSTGRESQL_DATABASE
              value: "test"
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-custom-config
              mountPath: /var/lib/pgsql/data/pg_hba.conf
              subPath: custom.pg_hba.conf #should be the name used in the ConfigMap
            - name: postgres-custom-config
              mountPath: /opt/app-root/src/postgresql-cfg/perf.conf
              subPath: custom.perf.conf #should be the name used in the ConfigMap
            - name: postgres-persistent-storage
              mountPath: /var/lib/pgsql/data
              readOnly: false
      volumes:
        - name: postgres-custom-config
          configMap:
            name: postgres-custom-config
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment
  namespace: postgres-db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432